#!/bin/bash
# 下载并编译 curl：O0–O3 均产出带 DWARF 的 ELF + 对应 .ll，供 binskel 完整对齐流水线共用
# 产出: curl_o0, curl_o0.ll, curl_o1, curl_o2, curl_o3
# 依赖: clang, llvm-link, llvm-dis；可选关闭 SSL 等以减小依赖: --without-ssl --without-zlib

set -e
CURL_VERSION="${CURL_VERSION:-8.7.1}"
BASE_DIR="${1:-$HOME/struclift_wsl/datasets/curl}"
DOWNLOAD_URL="https://curl.se/download/curl-${CURL_VERSION}.tar.gz"
TARBALL="/tmp/curl-${CURL_VERSION}.tar.gz"
DIR="${BASE_DIR}/curl-${CURL_VERSION}"

MD_CFLAGS="-O0 -g3 -fno-inline -fno-unroll-loops -fno-vectorize -fno-slp-vectorize -fstandalone-debug"
O1_CFLAGS="-O1 -g3 -fno-inline -fno-unroll-loops"
O2_CFLAGS="-O2 -g3 -fno-inline -fno-unroll-loops"
O3_CFLAGS="-O3 -g3 -fno-inline -fno-unroll-loops"

mkdir -p "$BASE_DIR"
cd "$BASE_DIR"

if [ ! -f "$TARBALL" ]; then
  echo "[1/5] 下载 curl-${CURL_VERSION} ..."
  wget -q -O "$TARBALL" "$DOWNLOAD_URL" || curl -sL -o "$TARBALL" "$DOWNLOAD_URL"
fi
if [ ! -d "$DIR" ]; then
  echo "[2/5] 解压 ..."
  tar -xzf "$TARBALL" -C "$BASE_DIR"
fi
cd "$DIR"

echo "[2b/5] 配置 (configure) ..."
export CC=clang
# 链接保留 DWARF（否则 extract_dwarf 为 0，仅靠 IR+反查表）
# 注意：仅 export LDFLAGS/CFLAGS 不够 —— Autoconf 生成的 Makefile 里写死的 CFLAGS 会覆盖环境变量。
# 必须在每次 make 时显式传入 CFLAGS= / LDFLAGS=（命令行变量优先级最高，且会传给子目录递归 make）。
CURL_EXTRA_LDFLAGS="${LDFLAGS:-} -g"
# configure 阶段也带上 -g，避免检测/模板与最终不一致（O1–O3 仍以 make 行内 CFLAGS 为准）
# 若系统无 ssl/zlib，可加: --without-ssl --without-zlib --disable-ldap
CFLAGS="-g3 -O0" LDFLAGS="$CURL_EXTRA_LDFLAGS" ./configure --disable-shared --without-ssl --without-zlib --disable-ldap --disable-manual 2>/dev/null || \
CFLAGS="-g3 -O0" LDFLAGS="$CURL_EXTRA_LDFLAGS" ./configure --disable-shared 2>/dev/null || \
CFLAGS="-g3 -O0" LDFLAGS="$CURL_EXTRA_LDFLAGS" ./configure

# make 时显式传入 CFLAGS/LDFLAGS（命令行覆盖 Makefile 内建值，子 make 也会继承）
curl_make() {
  local _cflags="$1"
  shift
  make CFLAGS="$_cflags" LDFLAGS="$CURL_EXTRA_LDFLAGS" "$@"
}

echo "[3/5] O0 (按 MD) + 产出 IR ..."
make clean 2>/dev/null || true
curl_make "$MD_CFLAGS"
CURL_REAL=""
[ -f src/.libs/curl ] && CURL_REAL="src/.libs/curl"
[ -z "$CURL_REAL" ] && [ -f src/curl ] && file src/curl 2>/dev/null | grep -q ELF && CURL_REAL="src/curl"
[ -z "$CURL_REAL" ] && [ -f src/curl ] && CURL_REAL="src/curl"
[ -f "$CURL_REAL" ] && cp -f "$CURL_REAL" curl_o0 || { echo "错误: 未生成 curl 可执行文件"; exit 1; }

# 产出 curl_o0.ll：lib/*.c + src/*.c 各自编译为 .bc 再 llvm-link（避免重名用子目录名前缀）
# 与 make 一致：HAVE_CONFIG_H + BUILDING_LIBCURL（库内用 struct 与公开 API 的 CURL* 一致）+ STRCONST（dynbuf 字面量）
BC_DIR="$DIR/.bc_o0"
rm -rf "$BC_DIR"
mkdir -p "$BC_DIR"
INC="-I. -Iinclude -Ilib -Isrc"
BC_CFLAGS="$MD_CFLAGS -DHAVE_CONFIG_H"
# 仅 lib 需要：库实现与公开头一致（struct Curl_easy* 等）、STRCONST 供 Curl_dyn_addn 等
# 用临时头文件定义 STRCONST，避免 -D 含括号在部分 shell 下被错误加引号导致 "macro name must be an identifier"
STRCONST_H="$BC_DIR/curl_strconst.h"
printf '%s\n' '/* generated by compile_curl.sh */' '#define STRCONST(x) (x,(size_t)(sizeof(x)-1))' > "$STRCONST_H"
BC_LIB_CFLAGS="$BC_CFLAGS -DBUILDING_LIBCURL -include $STRCONST_H"
echo "    [.ll] 编译 lib/*.c 与 src/*.c 为 .bc（curl 文件多，约 1–3 分钟）..."
for c in lib/*.c; do
  [ -f "$c" ] || continue
  bn=$(echo "$c" | tr '/' '_' | sed 's/\.c$/.bc/')
  clang $BC_LIB_CFLAGS $INC -emit-llvm -c "$c" -o "$BC_DIR/$bn" || true
done
for c in src/*.c; do
  [ -f "$c" ] || continue
  bn=$(echo "$c" | tr '/' '_' | sed 's/\.c$/.bc/')
  clang $BC_CFLAGS $INC -emit-llvm -c "$c" -o "$BC_DIR/$bn" || true
done
# 若未生成任何 .bc（例如 configure 异常），仅编 src 再试
if [ -z "$(ls -A "$BC_DIR" 2>/dev/null)" ]; then
  for c in src/*.c; do
    [ -f "$c" ] || continue
    bn=$(basename "$c" .c).bc
    clang $BC_CFLAGS -I. -Iinclude -Isrc -emit-llvm -c "$c" -o "$BC_DIR/$bn" || true
  done
fi
n_bc=$(find "$BC_DIR" -name "*.bc" 2>/dev/null | wc -l)
if [ "$n_bc" -gt 0 ]; then
  llvm-link "$BC_DIR"/*.bc -o "$DIR/curl_o0.bc"
  llvm-dis "$DIR/curl_o0.bc" -o "$DIR/curl_o0.ll"
  rm -rf "$BC_DIR" "$DIR/curl_o0.bc"
  echo "    -> $DIR/curl_o0, $DIR/curl_o0.ll"
else
  echo "    警告: 未生成 .bc，跳过 curl_o0.ll（O0 将仅用 DWARF）。请查看上方 clang 报错并修正 include/宏（如 -DHAVE_CONFIG_H）后重跑。"
  rm -rf "$BC_DIR"
fi

# 生成与 zlib 相同风格的 curl_oN.ll（供 O0–O3 全用 --llvm-ir）
emit_curl_ll() {
  local F="$1"
  local opt="$2"
  local BC_DIR="$DIR/.bc_o${opt}"
  rm -rf "$BC_DIR"
  mkdir -p "$BC_DIR"
  STRCONST_H="$BC_DIR/curl_strconst.h"
  printf '%s\n' '/* generated by compile_curl.sh */' '#define STRCONST(x) (x,(size_t)(sizeof(x)-1))' > "$STRCONST_H"
  BC_CFLAGS="$F -DHAVE_CONFIG_H"
  BC_LIB_CFLAGS="$BC_CFLAGS -DBUILDING_LIBCURL -include $STRCONST_H"
  for c in lib/*.c; do
    [ -f "$c" ] || continue
    bn=$(echo "$c" | tr '/' '_' | sed 's/\.c$/.bc/')
    clang $BC_LIB_CFLAGS $INC -emit-llvm -c "$c" -o "$BC_DIR/$bn" || true
  done
  for c in src/*.c; do
    [ -f "$c" ] || continue
    bn=$(echo "$c" | tr '/' '_' | sed 's/\.c$/.bc/')
    clang $BC_CFLAGS $INC -emit-llvm -c "$c" -o "$BC_DIR/$bn" || true
  done
  n_bc=$(find "$BC_DIR" -name "*.bc" 2>/dev/null | wc -l)
  if [ "$n_bc" -gt 0 ]; then
    llvm-link "$BC_DIR"/*.bc -o "$DIR/curl_o${opt}.bc"
    llvm-dis "$DIR/curl_o${opt}.bc" -o "$DIR/curl_o${opt}.ll"
    rm -rf "$BC_DIR" "$DIR/curl_o${opt}.bc"
    echo "    -> $DIR/curl_o${opt}.ll"
  else
    echo "    警告: curl_o${opt}.ll 未生成"
    rm -rf "$BC_DIR"
  fi
}

echo "[4/5] O1 / O2 / O3 (ELF + .ll，与 O0 同流水线) ..."
for opt in 1 2 3; do
  case $opt in 1) F="$O1_CFLAGS" ;; 2) F="$O2_CFLAGS" ;; 3) F="$O3_CFLAGS" ;; esac
  make clean 2>/dev/null || true
  curl_make "$F"
  CURL_REAL=""
  [ -f src/.libs/curl ] && CURL_REAL="src/.libs/curl"
  [ -z "$CURL_REAL" ] && [ -f src/curl ] && file src/curl 2>/dev/null | grep -q ELF && CURL_REAL="src/curl"
  [ -z "$CURL_REAL" ] && [ -f src/curl ] && CURL_REAL="src/curl"
  [ -f "$CURL_REAL" ] && cp -f "$CURL_REAL" "curl_o$opt" || true
  echo "    -> $DIR/curl_o$opt"
  emit_curl_ll "$F" "$opt"
done

echo "[5/5] 完成"
echo "  O0: $DIR/curl_o0  $DIR/curl_o0.ll"
echo "  O1/O2/O3: $DIR/curl_o1 + curl_o1.ll … curl_o3 + curl_o3.ll"
echo "  源码目录: $DIR (--src 指向此目录)"
if command -v readelf >/dev/null 2>&1; then
  echo "  DWARF 自检 (需见 .debug_line；否则 build_binskel 会显示 dwarf 条目数: 0):"
  for b in curl_o0 curl_o1 curl_o2 curl_o3; do
    [ -f "$DIR/$b" ] || continue
    if readelf -S "$DIR/$b" 2>/dev/null | grep -qE '\.debug_line'; then
      echo "    ✓ $b 含 .debug_line"
    else
      echo "    ✗ $b 缺少 .debug_line"
    fi
  done
fi
