#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Export source functions and current Stage2 A/B predicted skeletons.

This is for manual control-flow comparison.  It deliberately does not trust
old skeleton text stored in a v9/v10 JSONL.  The JSONL is used as the sample
pool and source/binary feature carrier; the AB skeleton is regenerated by
loading a Stage2 checkpoint, running current Module A/B, and serializing the
emitted skeleton with the current rule builder.
"""

from __future__ import annotations

import argparse
import collections
import json
import random
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import torch  # noqa: E402

import audit_stage2ab_skeleton_effect as effect  # noqa: E402
import augment_binskel_sft as sft_aug  # noqa: E402
import repack_modulec_v9_to_v10 as repack  # noqa: E402
from augment_binskel_sft_from_stage2 import (  # noqa: E402
    _load_stage2_model,
    _upgrade_skeleton_binary_context,
)
from struclift.data.binskel_jsonl import (  # noqa: E402
    collate_binskel_stage2_batch,
    move_binskel_batch_to_device,
)
from struclift.models.struclift import StrucLift  # noqa: E402


PATTERN_NAMES = {
    0: "sequential",
    1: "if_header",
    2: "if_then_body",
    3: "if_else_body",
    4: "loop_header",
    5: "loop_body",
    6: "loop_exit",
    7: "switch_header",
    8: "switch_case_body",
    9: "function_prologue_epilogue",
}


def _iter_jsonl(path: Path, limit: int = 0) -> Iterable[Tuple[int, Dict[str, Any]]]:
    with path.open("r", encoding="utf-8") as f:
        for i, line in enumerate(f, 1):
            if limit and i > limit:
                break
            line = line.strip()
            if line:
                yield i, json.loads(line)


def _apply_source_rewrites(
    row: Dict[str, Any],
    prefix_rewrites: Optional[List[Tuple[str, str]]],
) -> Dict[str, Any]:
    if not prefix_rewrites:
        return row
    out = dict(row)
    sf = out.get("source_file")
    if isinstance(sf, str) and sf:
        out["source_file"] = sft_aug._rewrite_source_path_string(sf, prefix_rewrites)
    return out


def _source_function_with_numbers(
    record: Dict[str, Any],
) -> Tuple[str, Optional[Tuple[int, int]]]:
    lt = repack._line_to_text(record.get("source_file"))
    if not lt:
        return "<source file unreadable>", None
    bounds = repack._function_body_line_range(record, lt)
    if bounds is None:
        return "<function bounds unavailable>", None
    lo, hi = bounds
    out: List[str] = []
    for ln in range(lo, hi + 1):
        if ln in lt:
            out.append(f"{ln:5d}: {lt[ln]}")
    return ("\n".join(out) if out else "<empty source range>"), bounds


def _source_control_meta(
    record: Dict[str, Any],
    *,
    source_control_filter: str,
) -> Dict[str, Any]:
    rows = effect._source_rows(record)
    parse_status = effect._source_parse_status(record, rows)
    active_lines = effect._active_source_lines(record)
    outline3 = effect._source_control_outline(
        rows,
        active_lines=active_lines,
        source_control_filter=source_control_filter,
    )
    outline_source = "statement_rows"
    rows_for_judgment = len(rows)
    if not rows and active_lines:
        fallback = effect._active_line_control_outline(
            record,
            active_lines,
            source_control_filter=source_control_filter,
        )
        if fallback or source_control_filter != "raw":
            outline3 = fallback
            outline_source = "active_line_fallback"
            rows_for_judgment = len(active_lines)
    src_seq = [(t, d) for t, d, _line in outline3]
    src_counts = effect._counts(src_seq)
    return {
        "source_statement_rows": len(rows),
        "source_rows_for_judgment": rows_for_judgment,
        "source_parse_status": parse_status,
        "source_outline_source": outline_source,
        "source_control_count": len(src_seq),
        "source_counts": dict(src_counts),
        "source_outline": effect._source_outline_lines(outline3, limit=160),
        "active_source_lines": len(active_lines),
    }


def _n_bb(row: Dict[str, Any]) -> int:
    return effect._n_bb(row)


def _pattern_label_summary(labels: Sequence[int]) -> str:
    counts: Dict[int, int] = {}
    for x in labels:
        lab = int(x)
        counts[lab] = counts.get(lab, 0) + 1
    parts = [
        f"{PATTERN_NAMES.get(lab, f'unknown_{lab}')}={counts[lab]}"
        for lab in sorted(counts)
    ]
    return ", ".join(parts) if parts else "<empty pattern labels>"


def _pattern_label_sequence(labels: Sequence[int], max_items: int = 220) -> str:
    vals: List[str] = []
    for i, lab0 in enumerate(labels[:max_items]):
        lab = int(lab0)
        vals.append(f"BB_{i}:{PATTERN_NAMES.get(lab, f'unknown_{lab}')}")
    if len(labels) > max_items:
        vals.append("...")
    return "\n".join(vals)


def _control_meta_from_skeleton(skeleton: str) -> Dict[str, Any]:
    pred_seq = effect._control_outline_from_text(skeleton)
    pred_counts = effect._counts(pred_seq)
    return {
        "pred_control_count": len(pred_seq),
        "pred_counts": dict(pred_counts),
        "pred_outline": effect._outline_lines(pred_seq, limit=160),
        "bb_stats": effect._bb_marker_stats(skeleton, 10**9),
    }


@torch.inference_mode()
def _run_stage2_ab_batch(
    model: StrucLift,
    records: List[Dict[str, Any]],
    device: torch.device,
    *,
    use_m_gt_for_ab: bool,
) -> List[Tuple[Optional[Any], Optional[List[int]], Optional[List[float]], str]]:
    try:
        batch = collate_binskel_stage2_batch(records)
        batch = move_binskel_batch_to_device(batch, device)
        out = model.encode(
            bin_opcodes=batch["bin_opcodes"],
            bin_operand_types=batch["bin_operand_types"],
            bin_operand_values=batch["bin_operand_values"],
            bin_block_lengths=batch["bin_block_lengths"],
            bin_edge_index=batch["bin_edge_index"],
            bin_edge_type=batch["bin_edge_type"],
            bin_struct_features=batch["bin_struct_features"],
            bin_batch=batch.get("bin_batch"),
            src_token_ids=batch.get("src_token_ids"),
            src_stmt_lengths=batch.get("src_stmt_lengths"),
            src_edge_index=batch.get("src_edge_index"),
            src_edge_type=batch.get("src_edge_type"),
            src_ast_types=batch.get("src_ast_types"),
            src_compound_id=batch.get("src_compound_id"),
            src_batch=batch.get("src_batch"),
            bin_adj=batch.get("adj_bin"),
            src_adj=batch.get("adj_src_gt"),
            M_gt=batch.get("M_gt") if use_m_gt_for_ab else None,
            run_alignment=True,
        )

        labels_all = out.pattern_logits.argmax(dim=-1).detach().cpu().tolist()
        probs_all = torch.softmax(out.pattern_logits, dim=-1).amax(dim=-1).detach().cpu().tolist()
        skels = list(out.skeleton_list or [])

        res: List[Tuple[Optional[Any], Optional[List[int]], Optional[List[float]], str]] = []
        off = 0
        for i, rec in enumerate(records):
            n = _n_bb(rec)
            labels = [int(x) for x in labels_all[off : off + n]]
            probs = [float(x) for x in probs_all[off : off + n]]
            off += n
            skel = skels[i] if i < len(skels) else None
            if skel is None:
                res.append((None, labels, probs, "Stage2 Module B did not emit skeleton"))
            else:
                res.append((skel, labels, probs, ""))
        return res
    except RuntimeError as e:
        if len(records) > 1 and ("out of memory" in str(e).lower() or "cuda" in str(e).lower()):
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            mid = len(records) // 2
            return (
                _run_stage2_ab_batch(
                    model,
                    records[:mid],
                    device,
                    use_m_gt_for_ab=use_m_gt_for_ab,
                )
                + _run_stage2_ab_batch(
                    model,
                    records[mid:],
                    device,
                    use_m_gt_for_ab=use_m_gt_for_ab,
                )
            )
        return [(None, None, None, f"Stage2 A/B failed: {e}") for _ in records]
    except Exception as e:
        return [(None, None, None, f"Stage2 A/B failed: {type(e).__name__}: {e}") for _ in records]


def _write_example(
    wf: Any,
    idx: int,
    line_no: int,
    row: Dict[str, Any],
    source_text: str,
    bounds: Tuple[int, int],
    source_meta: Dict[str, Any],
    skeleton_text: str,
    labels: Sequence[int],
    label_conf: Optional[Sequence[float]],
    skel_obj: Any,
) -> None:
    pred_meta = _control_meta_from_skeleton(skeleton_text)
    src_counts = collections.Counter(source_meta.get("source_counts") or {})
    pred_counts = collections.Counter(pred_meta.get("pred_counts") or {})
    n_bb = _n_bb(row)
    bb_stats = effect._bb_marker_stats(skeleton_text, n_bb)
    conf_vals = [float(x) for x in (label_conf or [])]
    conf_line = "n/a"
    if conf_vals:
        conf_line = (
            f"min/median/max={min(conf_vals):.3f}/"
            f"{effect._median(conf_vals):.3f}/{max(conf_vals):.3f}"
        )

    wf.write("\n" + "=" * 120 + "\n")
    wf.write(
        f"example = {idx}  input_line = {line_no}  func = {row.get('func_name')}\n"
    )
    wf.write(f"source_file = {row.get('source_file')}\n")
    wf.write(f"source_bounds = {bounds[0]}-{bounds[1]}\n")
    wf.write("skeleton_source = current_stage2_ab_prediction_plus_current_rule_builder\n")
    wf.write(f"bb = {n_bb}\n")
    wf.write(
        f"source_parse = {source_meta.get('source_parse_status')}  "
        f"source_ref = {source_meta.get('source_outline_source')}  "
        f"src_rows = {source_meta.get('source_statement_rows')}  "
        f"active_source_lines = {source_meta.get('active_source_lines')}\n"
    )
    wf.write(
        f"ctrl(pred/source) = {pred_meta.get('pred_control_count')}/"
        f"{source_meta.get('source_control_count')}  "
        f"gaps(if,loop,switch)=("
        f"{int(pred_counts.get('if', 0)) - int(src_counts.get('if', 0))},"
        f"{int(pred_counts.get('loop', 0)) - int(src_counts.get('loop', 0))},"
        f"{int(pred_counts.get('switch', 0)) - int(src_counts.get('switch', 0))})\n"
    )
    wf.write(
        f"bb_cover = {bb_stats.get('bb_covered')}/{n_bb}  "
        f"bb_missing = {bb_stats.get('bb_missing')}  "
        f"bb_duplicated_first20 = {bb_stats.get('bb_duplicated')}\n"
    )
    wf.write(f"ab_pred_10class_label_counts = {_pattern_label_summary(labels)}\n")
    wf.write(f"ab_pred_10class_label_confidence = {conf_line}\n")
    wf.write(f"stage2_skeleton_reliability = {getattr(skel_obj, 'reliability', None)}\n")
    wf.write(f"stage2_skeleton_build_stats = {getattr(skel_obj, 'build_stats', None)}\n")

    wf.write("\n-- SOURCE CONTROL OUTLINE --\n")
    wf.write("\n".join(source_meta.get("source_outline") or ["<none>"]) + "\n")

    wf.write("\n-- AB SKELETON CONTROL OUTLINE --\n")
    wf.write("\n".join(pred_meta.get("pred_outline") or ["<none>"]) + "\n")

    wf.write("\n-- AB PREDICTED 10CLASS BB LABEL SEQUENCE --\n")
    wf.write(_pattern_label_sequence(labels) + "\n")

    wf.write("\n-- REAL SOURCE FUNCTION --\n")
    wf.write(source_text.rstrip() + "\n")

    wf.write("\n-- CURRENT AB GENERATED FULL SKELETON --\n")
    wf.write((skeleton_text or "<missing skeleton>").rstrip() + "\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--jsonl", "--input", dest="jsonl", type=Path, required=True)
    ap.add_argument("--out", "--output", dest="out", type=Path, required=True)
    ap.add_argument("--stage2-ckpt", type=Path, required=True)
    ap.add_argument("--device", type=str, default="cuda")
    ap.add_argument("--num-examples", type=int, default=100)
    ap.add_argument("--limit", type=int, default=0, help="0 means scan the whole jsonl")
    ap.add_argument("--batch-size", type=int, default=8)
    ap.add_argument("--seed", type=int, default=527)
    ap.add_argument("--random-sample", action="store_true")
    ap.add_argument("--candidate-pool-size", type=int, default=600)
    ap.add_argument(
        "--source-control-filter",
        choices=["raw", "bb-start-line", "bb-range"],
        default="bb-start-line",
    )
    ap.add_argument("--min-source-controls", type=int, default=1)
    ap.add_argument("--allow-duplicates", action="store_true")
    ap.add_argument(
        "--include-fallback-source-outline",
        action="store_true",
        help=(
            "Allow samples whose source control outline is active-line fallback. "
            "Full source function bounds are still required."
        ),
    )
    ap.add_argument(
        "--use-m-gt-for-ab",
        action="store_true",
        help="Feed M_gt into Module B. Default is off, matching current inference-like AB.",
    )
    ap.add_argument(
        "--rewrite-source-prefix",
        nargs=2,
        metavar=("FROM_PREFIX", "TO_PREFIX"),
        action="append",
        dest="prefix_pairs",
    )
    args = ap.parse_args()

    prefix_pairs: Optional[List[Tuple[str, str]]] = None
    if args.prefix_pairs:
        prefix_pairs = [(str(a), str(b)) for a, b in args.prefix_pairs]

    rng = random.Random(int(args.seed))
    pool_target = max(int(args.num_examples), int(args.candidate_pool_size))
    candidates: List[Tuple[int, Dict[str, Any], str, Tuple[int, int], Dict[str, Any]]] = []
    seen = set()
    scanned = 0
    eligible = 0
    skipped: "collections.Counter[str]" = collections.Counter()

    jsonl = args.jsonl.expanduser().resolve()
    for line_no, raw in _iter_jsonl(jsonl, int(args.limit)):
        scanned += 1
        row = _apply_source_rewrites(raw, prefix_pairs)
        source_text, bounds = _source_function_with_numbers(row)
        if bounds is None:
            skipped["source_bounds_unavailable"] += 1
            continue
        key = (str(row.get("source_file") or ""), str(row.get("func_name") or ""), bounds)
        if not args.allow_duplicates and key in seen:
            skipped["duplicate_function"] += 1
            continue
        source_meta = _source_control_meta(
            row,
            source_control_filter=str(args.source_control_filter),
        )
        if int(source_meta.get("source_control_count") or 0) < int(args.min_source_controls):
            skipped["no_source_control"] += 1
            continue
        if (
            not args.include_fallback_source_outline
            and source_meta.get("source_outline_source") != "statement_rows"
        ):
            skipped["fallback_source_outline"] += 1
            continue
        seen.add(key)
        item = (line_no, row, source_text, bounds, source_meta)
        eligible += 1
        if args.random_sample:
            if len(candidates) < pool_target:
                candidates.append(item)
            else:
                j = rng.randrange(eligible)
                if j < pool_target:
                    candidates[j] = item
        else:
            candidates.append(item)
            if len(candidates) >= pool_target:
                break

    if args.random_sample:
        rng.shuffle(candidates)

    device = torch.device(args.device if torch.cuda.is_available() or args.device == "cpu" else "cpu")
    if device.type == "cuda":
        torch.backends.cuda.matmul.allow_tf32 = True
    model = _load_stage2_model(args.stage2_ckpt.expanduser().resolve(), device)

    chosen: List[
        Tuple[
            int,
            Dict[str, Any],
            str,
            Tuple[int, int],
            Dict[str, Any],
            str,
            List[int],
            Optional[List[float]],
            Any,
        ]
    ] = []
    ab_errors: "collections.Counter[str]" = collections.Counter()

    bs = max(1, int(args.batch_size))
    for start in range(0, len(candidates), bs):
        chunk = candidates[start : start + bs]
        rows = [x[1] for x in chunk]
        results = _run_stage2_ab_batch(
            model,
            rows,
            device,
            use_m_gt_for_ab=bool(args.use_m_gt_for_ab),
        )
        for item, (skel, labels, conf, err) in zip(chunk, results):
            line_no, row, source_text, bounds, source_meta = item
            if skel is None or not labels:
                ab_errors[str(err).split(":", 1)[0] or "stage2_ab_failed"] += 1
                continue
            try:
                skel, _readable = _upgrade_skeleton_binary_context(skel, row)
            except Exception:
                pass
            skeleton_text = str(getattr(skel, "skeleton_text", "") or "")
            if hasattr(sft_aug, "_format_skeleton_text_for_prompt"):
                skeleton_text = sft_aug._format_skeleton_text_for_prompt(skeleton_text)
            if not skeleton_text.strip():
                ab_errors["empty_skeleton_text"] += 1
                continue
            chosen.append(
                (
                    line_no,
                    row,
                    source_text,
                    bounds,
                    source_meta,
                    skeleton_text,
                    [int(x) for x in labels],
                    list(conf) if conf is not None else None,
                    skel,
                )
            )
            if len(chosen) >= int(args.num_examples):
                break
        if len(chosen) >= int(args.num_examples):
            break

    out = args.out.expanduser().resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as wf:
        wf.write("===== CURRENT STAGE2AB PREDICTED SKELETON VS REAL SOURCE EXPORT =====\n")
        wf.write(f"input = {jsonl}\n")
        wf.write(f"stage2_ckpt = {args.stage2_ckpt.expanduser().resolve()}\n")
        wf.write("skeleton_source = current_stage2_ab_prediction_plus_current_rule_builder\n")
        wf.write(f"use_m_gt_for_ab = {bool(args.use_m_gt_for_ab)}\n")
        wf.write(f"device = {device}\n")
        wf.write(f"scanned = {scanned}\n")
        wf.write(f"eligible_source_control_full_source = {eligible}\n")
        wf.write(f"candidate_pool = {len(candidates)}\n")
        wf.write(f"exported = {len(chosen)}\n")
        wf.write(f"requested = {int(args.num_examples)}\n")
        wf.write(f"random_sample = {bool(args.random_sample)}\n")
        wf.write(f"seed = {int(args.seed)}\n")
        wf.write(f"source_control_filter = {args.source_control_filter}\n")
        wf.write(f"min_source_controls = {int(args.min_source_controls)}\n")
        wf.write(f"allow_duplicates = {bool(args.allow_duplicates)}\n")
        wf.write(f"include_fallback_source_outline = {bool(args.include_fallback_source_outline)}\n")
        wf.write(f"skipped_before_ab = {dict(skipped)}\n")
        wf.write(f"stage2_ab_errors = {dict(ab_errors)}\n")

        for idx, (
            line_no,
            row,
            source_text,
            bounds,
            source_meta,
            skeleton_text,
            labels,
            conf,
            skel,
        ) in enumerate(chosen):
            _write_example(
                wf,
                idx,
                line_no,
                row,
                source_text,
                bounds,
                source_meta,
                skeleton_text,
                labels,
                conf,
                skel,
            )

    print(f"saved_to = {out}")
    print(f"scanned = {scanned}")
    print(f"eligible = {eligible}")
    print(f"candidate_pool = {len(candidates)}")
    print(f"exported = {len(chosen)}")
    print(f"skipped_before_ab = {dict(skipped)}")
    print(f"stage2_ab_errors = {dict(ab_errors)}")


if __name__ == "__main__":
    main()
